-- AlterTable
ALTER TABLE "Hotels" ALTER COLUMN "hotelName" DROP NOT NULL,
ALTER COLUMN "addressId" DROP NOT NULL,
ALTER COLUMN "perNight" DROP NOT NULL,
ALTER COLUMN "numberOfRooms" DROP NOT NULL,
ALTER COLUMN "hasParking" DROP NOT NULL,
ALTER COLUMN "hasPools" DROP NOT NULL,
ALTER COLUMN "hasWifi" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "numberOfEmptyRooms" DROP NOT NULL,
ALTER COLUMN "hasBalcony" DROP NOT NULL,
ALTER COLUMN "hasGarden" DROP NOT NULL,
ALTER COLUMN "hasGrummingEqupments" DROP NOT NULL,
ALTER COLUMN "hasKitchen" DROP NOT NULL,
ALTER COLUMN "hasTv" DROP NOT NULL,
ALTER COLUMN "hasWashingMachine" DROP NOT NULL,
ALTER COLUMN "hasWorkSpace" DROP NOT NULL,
ALTER COLUMN "roomType" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Users" ADD COLUMN     "GovID" INTEGER DEFAULT 0,
ADD COLUMN     "phoneNumber" INTEGER DEFAULT 0;
